// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.03 at 04:42:11 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.consol.com/schemas/bookstore", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.accenture.citrus.bookstore.model;
